LIBUAPI_SITE_METHOD = local
LIBUAPI_SITE = $(PLATFORM_PATH)/../../../platform/allwinner/display/libuapi

LIBUAPI_LICENSE = GPLv2+, GPLv3+
LIBUAPI_LICENSE_FILES = Copyright COPYING
LIBUAPI_INSTALL_STAGING = YES

KERNEL_VERSION = CONF_KERNEL_VERSION_3_10
KERNEL_PATCHVER = $(subst linux-,,$(LICHEE_KERN_VER))
#config the kernel version,which depends on $(KERNEL_PATCHVER)
ifeq ($(KERNEL_PATCHVER),3.4)
	KERNEL_VERSION = CONF_KERNEL_VERSION_3_4
endif

ifeq ($(KERNEL_PATCHVER),3.10)
	KERNEL_VERSION = CONF_KERNEL_VERSION_3_10
endif

ifeq ($(KERNEL_PATCHVER),4.4)
	KERNEL_VERSION = CONF_KERNEL_VERSION_4_4
endif

ifeq ($(KERNEL_PATCHVER),4.9)
	KERNEL_VERSION = CONF_KERNEL_VERSION_4_9
endif

ifeq ($(KERNEL_PATCHVER),5.4)
	KERNEL_VERSION = CONF_KERNEL_VERSION_5_4
endif

ifeq ($(KERNEL_PATCHVER),5.15)
	KERNEL_VERSION = CONF_KERNEL_VERSION_5_15
	LIBUAPI_CFLAGS+=-DCONF_USE_DMA_HEAP
endif
#end config the kernel version

ifeq ($(SUNXI_DISPLAY_TWO),y)
LIBUAPI_CFLAGS+=-D__SUNXI_DISPLAY2__
LIBUAPI_CFLAGS+=-D$(KERNEL_VERSION)
ifeq ($(LICHEE_USE_INDEPENDENT_BSP),true)
LIBUAPI_CFLAGS+=-I$(LICHEE_BSP_DIR)/include/video
else
LIBUAPI_CFLAGS+=-I$(LICHEE_KERN_DIR)/include/video
endif
endif
ifeq ($(SUNXI_DISPLAY_ONE),y)
LIBUAPI_CFLAGS+=-D__SUNXI_DISPLAY__
LIBUAPI_CFLAGS+=-D$(KERNEL_VERSION)
endif

ifeq ($(SUNXI_ALLOC_CMA),y)
LIBUAPI_CFLAGS+=-DCONF_KERNEL_CMA
endif
ifeq ($(SUNXI_ALLOC_IOMMU),y)
LIBUAPI_CFLAGS+=-DCONF_KERNEL_IOMMU
endif

ifeq ($(LUAPI_LAYER_ALLOC_CHN),y)
LIBUAPI_CFLAGS+=-DLUAPI_LAYER_ALLOC_CHN
endif
ifeq ($(LUAPI_LAYER_ALLOC_LAY),y)
LIBUAPI_CFLAGS+=-DLUAPI_LAYER_ALLOC_LAY
endif

ifeq ($(SUNXI_DISPLAY_GPU),y)
	#LIBUAPI_CFLAGS+=-DSUNXI_DISPLAY_GPU
	LIBUAPI_CFLAGS+=-DSUNXI_DISPLAY_GPU -DSUNXI_DISPLAY_GPU_BUF
	LIBUAPI_LDFLAGS+=-lEGL -lMali -lGLESv2
else
	TPLAYER_EXTRA_CFLAGS+=-DSUNXI_DISPLAY_DE
endif

PKG_INSTALL_DIR = $(@D)/install

define LIBUAPI_BUILD_CMDS
	[ ! -e PKG_INSTALL_DIR ] && mkdir -p $(PKG_INSTALL_DIR)
	make -C $(@D)/src\
		ARCH="$(TARGET_ARCH)" \
		AR="$(TARGET_AR)" \
		CC="$(TARGET_CC)" \
		CXX="$(TARGET_CXX)" \
		CFLAGS="$(LIBUAPI_CFLAGS)" \
		LDFLAGS="$(LIBUAPI_LDFLAGS)" \
		INSTALL_PREFIX="$(PKG_INSTALL_DIR)" \
		all

endef

define LIBUAPI_INSTALL_STAGING_CMDS
	$(INSTALL) -D -m 0644 $(PKG_INSTALL_DIR)/usr/lib/* $(STAGING_DIR)/usr/lib/
	$(INSTALL) -D -m 0644 $(PKG_INSTALL_DIR)/usr/include/* $(STAGING_DIR)/usr/include/
endef

define LIBUAPI_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0644 $(PKG_INSTALL_DIR)/usr/lib/* $(TARGET_DIR)/usr/lib/
endef
$(eval $(generic-package))
