#!/bin/sh
#

case "$1" in
    start)
        echo /sbin/mdev > /proc/sys/kernel/hotplug
        mdev -s
        ;;
    stop)]
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
