#!/bin/sh
#
# Start the mount udisk
#
tinymix set "HPOUT Switch" 1
tinymix set "SPK Switch" 1
tinymix set "MIC3 Switch" 1 
case "$1" in
    start)
        source /etc/partition_op.sh

        do_device_node_switch
        do_format_filesystem /dev/by-name/UDISK vfat

        mkdir -p /mnt/UDISK
        do_mount_filesystem /dev/by-name/UDISK /mnt/UDISK
        ;;
    stop)]
        ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
        ;;
esac
udhcpc -i eth0 &
exit 0
